name: build-env
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.2.0
  - xeus-python
  - pip:
    - jupyterlite-pyodide-kernel
